pipeline:
  docker:
    image: plugins/docker
    dockerfile: Dockerfile
    username: ${DOCKER_USER}
    password: ${DOCKER_PASSWORD}
    email: harshal@infracloud.io
    repo: harshals/demo-go-app
    tags: "${DRONE_BRANCH}.${DRONE_BUILD_NUMBER}"
  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: https://104.154.70.149
    kubernetes_token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbVJsWm1GMWJIUXRkRzlyWlc0dGFqSnpaR1lpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1dVlXMWxJam9pWkdWbVlYVnNkQ0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG5WcFpDSTZJakF6TkdJeVptTTFMVEZsT0RrdE1URmxOeTA1WmpBMExUUXlNREV3WVRnd01ERXpPQ0lzSW5OMVlpSTZJbk41YzNSbGJUcHpaWEoyYVdObFlXTmpiM1Z1ZERwa1pXWmhkV3gwT21SbFptRjFiSFFpZlEuSi1fMkhKcjBDVHJyN2YwWTIxLUxnLTVza054N2FTMGFPNHNjU29xYkFfcWFVUWlXMzdCUkFiUjU4NTBiRnozT1NrZU9oajJ5NGhueUp2RFR5RThBX200aGxocXhYZU5mT3pqMTl1UkFvdUN3bkk0a3lGNnpFV3NkRDFWT2NKLU5pMGk3U3hWMXZ1QkUtdks5eEhZUmJacEVWaEhYVkdlNGZINmtZQVAtbHdnTWxMSlp6bjlhWHRvLTlUb1RtdDZDcTlYMlQ5NE14Y0oxZHBqNDd2TmNaWjg1NkpSRU00NXFKYUctMjJ6anRVVWxLNy1lVmlOWnllV1h0OE9xYVRqNk5HeTIwMV9rQ04zcl9WdXFiY0RBRVB5cFZzeHBDRDk4cUFKNndxVVBQQm5BNUd2Z0JlNUdTOXVzS2ZxTkFvVmRhaGJYX3h5N1dSZGRTWDNMbUpUNTFn
    namespace: demo-app
    deployment: demo-app-prod
    repo: harshals/demo-go-app
    container: demo-app-prod
    tag: "${DRONE_BRANCH}.${DRONE_BUILD_NUMBER}"
