pipeline:
  docker:
    image: plugins/docker
    dockerfile: Dockerfile
    username: ${DOCKER_USER}
    password: ${DOCKER_PASSWORD}
    email: harshal@infracloud.io
    repo: harshals/demo-go-app
    tags: "${DRONE_BRANCH}.${DRONE_BUILD_NUMBER}"
  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: https://104.154.70.149
    kubernetes_token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbVJ5YjI1bExYUnZhMlZ1TFRGMk1IaHRJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpYSjJhV05sTFdGalkyOTFiblF1Ym1GdFpTSTZJbVJ5YjI1bElpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVkV2xrSWpvaU1UazVORE0xWmpJdE1XVTRaQzB4TVdVM0xUbG1NRFF0TkRJd01UQmhPREF3TVRNNElpd2ljM1ZpSWpvaWMzbHpkR1Z0T25ObGNuWnBZMlZoWTJOdmRXNTBPbVJsWm1GMWJIUTZaSEp2Ym1VaWZRLmhzVEQ4dWluTlBsVFhGVVZ6a3RWeV9LcF84MWFqTlZYejM2bk85OWhmdW1MOGdUVmI0NWFuXzk5VjRIemlFelBiaGVaZ0c1RzMxR1hJMzB6cTYwUE8ya0pBaHY5cHZSUzFEaHJ6Q1ZtalNNTktrbUxKOWcxSFpteGEwSG9QaWRlS09lcFV4Sk90Mm9HMmx0Rmk5T2VGa0lQckVsUzdGcnFkRXlYOW11cF96Ymg4djdxMF9wUFFubWxZSUwwNlNTMUVnTVhGeTZMNUNMWmswQXVCZkUtaHM0bl9lVy1mbmZHVUdvcWhfM3oyeFVRTV9tRkx1c0pEWXM1SWJ1UTFDclRjZ1d0TnRucklyeU5QWUFQUUNJQXlBX20yNUtnVWtwUXdwa0pRcEMySVVsRHhZaEF5ek51dDBwYy1ubGJKVzRNUnc1MF9uYW9tdTduMUt5M0ExMC1XZw==
    namespace: demo-app
    deployment: demo-app-prod
    repo: harshals/demo-go-app
    container: demo-app-prod
    tag: "${DRONE_BRANCH}.${DRONE_BUILD_NUMBER}"
