node{
        checkout scm
        stage('Helm Init'){
                sh 'helm init --client-only --service-account=tiller'
        }
        stage('Dependency Build'){
                sh 'helm dependency build helm-charts/demo-go-app
        }
        stage('Deploy Chart'){
                sh "helm status dev-demo 2>/dev/null || helm install --name dev-demo --namespace default -f helm-charts/demo-go-app/dev_demo.yaml helm-charts/demo-go-app"
                sh "helm upgrade dev-demo -f helm-charts/demo-go-app/dev_demo.yaml helm-charts/demo-go-app"
        }

}

